### PR TITLE
rev16 rough

### PR DESCRIPTION
**Pull request by boelle**
might change regulator

### CODE REVIEW

**Comment by DamonHD** [comment]
I'm seeing changes to REV10.  Is that intended?

**Comment by DamonHD** [comment]
Or at least something called rev10 is a folder called REV16.

Also, please can we reserve REVxx numbers to boards with CPUs on?

**Comment by boelle** [comment]
i just forgot to change the filename

so rename it to rev16

2016-02-25 15:03 GMT+01:00 Damon Hart-Davis <notifications@github.com>:

**Comment by DamonHD** [comment]
OK I'll cancel this and you can use the structure under REV15 instead.

**Pull request closed without merging**
